### ISSUE TITLE
Include BOM and Gerber Files

### ISSUE THREAD

**Issue by mizz141** [ploopyco/thumb-trackball#1]
Would it be possible to have a Bill of Materials and Gerber files available along with the propietary PCBLIB and SCHLIB files?

**Comment by IBNobody** [comment]
@mizz141 You can generate these yourself for FREE by uploading the design into Altium365, provided free via Altium's circuitmaker app.

[Thumb-R1_001_gerber.zip](https://github.com/ploopyco/thumb-trackball/files/7714505/Thumb-R1_001_gerber.zip)
[Thumb-R1_001_BOM.csv](https://github.com/ploopyco/thumb-trackball/files/7714506/Thumb-R1_001_BOM.csv)

This is just the electrical BOM, by the way.

@ploopyco You can put these in the repo if you want, but I would recommend that you generate them yourself.
